// Code generated by MockGen. DO NOT EDIT.
// Source: http_client.go

// Package reslock is a generated GoMock package.
package reslock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockrequestDoer is a mock of requestDoer interface.
type MockrequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockrequestDoerMockRecorder
}

// MockrequestDoerMockRecorder is the mock recorder for MockrequestDoer.
type MockrequestDoerMockRecorder struct {
	mock *MockrequestDoer
}

// NewMockrequestDoer creates a new mock instance.
func NewMockrequestDoer(ctrl *gomock.Controller) *MockrequestDoer {
	mock := &MockrequestDoer{ctrl: ctrl}
	mock.recorder = &MockrequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrequestDoer) EXPECT() *MockrequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockrequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockrequestDoerMockRecorder) Do(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockrequestDoer)(nil).Do), req)
}
